'\" t
.\"     Title: login
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 19.11.2015
.\"    Manual: Dienstprogramme f\(:ur Benutzer
.\"    Source: shadow-utils 4.2
.\"  Language: German
.\"
.TH "LOGIN" "1" "19.11.2015" "shadow\-utils 4\&.2" "Dienstprogramme f\(:ur Benutzer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
login \- startet eine Sitzung auf dem System
.SH "\(:UBERSICHT"
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIRechner\fR] [\fIBenutzername\fR] [\fIENV=VAR\fR...]
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIRechner\fR] \-f \fIBenutzername\fR
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] \-r\ \fIRechner\fR
.SH "BESCHREIBUNG"
.PP
Das Programm
\fBlogin\fR
wird verwendet, um eine neue Sitzung auf dem System zu starten\&. Es wird normalerweise automatisch als Antwort auf die
\fIlogin:\fR\-Eingabeaufforderung auf dem Terminal des Benutzers ausgef\(:uhrt\&.
\fBlogin\fR
kann von der Shell besonders behandelt werden und kann nicht als Subprozess gestartet werden\&. Wenn
\fBlogin\fR
von einer Shell aufgerufen wird, sollte es als
\fBexec login\fR
ausgef\(:uhrt werden, so dass die aktuelle Shell des Benutzers beendet wird (und somit verhindert wird, dass der neue Benutzer in die Sitzung des alten zur\(:uckkehren kann)\&. Der Versuch, von einer Shell au\(sser der Anmelde\-Shell
\fBlogin\fR
auszuf\(:uhren, wird eine Fehlermeldung erzeugen\&.
.PP
Falls erforderlich, wird der Benutzer anschlie\(ssend nach einem Passwort gefragt\&. Dieses wird w\(:ahrend der Eingabe nicht angezeigt\&. Es sind nur eine kleine Anzahl von Anmeldeversuchen zul\(:assig, ehe
\fBlogin\fR
abbricht und die Kommunikation getrennt wird\&.
.PP
Falls der Passwortverfall f\(:ur Ihr Konto aktiviert wurde, kann es sein, dass Sie vor der weiteren Nutzung nach einem neuen Passwort gefragt werden\&. Sie m\(:ussen Ihr altes und neues Passwort angegeben, bevor Sie fortfahren k\(:onnen\&. In der Dokumentation zu
\fBpasswd\fR(1)
finden sich weitere Informationen\&.
.PP
Die Benutzer\- und Gruppen\-IDs werden gem\(:a\(ss den Werten in
/etc/passwd
gesetzt\&. Die Werte f\(:ur
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$PATH\fR,
\fB$LOGNAME\fR
und
\fB$MAIL\fR
werden ebenfalls entsprechend den Feldern im Passworteintrag gesetzt\&. Werte f\(:ur ulimit, umask und nice k\(:onnen ebenfalls gem\(:a\(ss den Werten im GECOS\-Feld gesetzt werden\&.
.PP
Bei einigen Installationen wird anf\(:anglich die Umgebungsvariable
\fB$TERM\fR
entsprechend dem Terminaltyp Ihrer tty\-Zeile, wie sie in
/etc/ttytype
angegeben ist, gesetzt\&.
.PP
Ein Startskript f\(:ur Ihren Befehlsinterpreter kann auch ausgef\(:uhrt werden\&. Sehen Sie bitte in den entsprechenden Handbuchseiten f\(:ur weitere Informationen dar\(:uber nach\&.
.PP
Eine Subsystem\-Anmeldung wird durch einen \(Fc*\(Fo als erstes Zeichen der Anmelde\-Shell gekennzeichnet\&. Das angegebene Home\-Verzeichnis wird als Wurzel f\(:ur das Dateisystem verwendet, auf welchem der Benutzer tats\(:achlich angemeldet ist\&.
.PP
Es liegt NICHT in der Verantwortung von
\fBlogin\fR, Benutzer aus der utmp\-Datei zu entfernen\&. Sowohl
\fBgetty\fR(8)
als auch
\fBinit\fR(8)
sind daf\(:ur zust\(:andig, die offenkundige Eigent\(:umerstellung einer Terminalsitzung aufzur\(:aumen\&. Falls Sie
\fBlogin\fR
von der Shell ohne
\fBexec\fR
verwenden, wird der Benutzer, den Sie verwenden, weiterhin als angemeldet erscheinen, obwohl Sie die \(Fcuntergeordnete Sitzung\(Fo beendet haben\&.
.SH "OPTIONEN"
.PP
\fB\-f\fR
.RS 4
Keine Authentifizierung durchf\(:uhren, Benutzer ist bereits angemeldet\&.
.sp
Hinweis: In diesem Fall muss
\fIBenutzername\fR
angegeben werden\&.
.RE
.PP
\fB\-h\fR
.RS 4
Name des entfernt stehenden Rechners f\(:ur die Anmeldung
.RE
.PP
\fB\-p\fR
.RS 4
beh\(:alt die Umgebungseinstellungen bei
.RE
.PP
\fB\-r\fR
.RS 4
f\(:uhrt das Autologin\-Protokoll f\(:ur rlogin aus
.RE
.PP
Die Optionen
\fB\-r\fR,
\fB\-h\fR
und
\fB\-f\fR
k\(:onnen nur verwendet werden, wenn
\fBlogin\fR
von Root ausgef\(:uhrt wird\&.
.SH "WARNUNGEN"
.PP
Diese Version von
\fBlogin\fR
hat viele Optionen f\(:ur die Kompilierung, wobei eventuell nicht alle Optionen auf allen Systemen verwendet werden\&.
.PP
Der Ort der Konfigurationsdateien kann je nach Konfiguration des Systems unterschiedlich sein\&.
.PP
Es liegt NICHT in der Verantwortung von
\fBlogin\fR, Benutzer aus der utmp\-Datei zu entfernen\&. Sowohl
\fBgetty\fR(8)
als auch
\fBinit\fR(8)
sind daf\(:ur zust\(:andig, die offenkundige Eigent\(:umerstellung einer Terminalsitzung aufzur\(:aumen\&. Falls Sie
\fBlogin\fR
von der Shell ohne
\fBexec\fR
verwenden, wird der Benutzer, den Sie verwenden, weiterhin als angemeldet erscheinen, obwohl Sie die \(Fcuntergeordnete Sitzung\(Fo beendet haben\&.
.PP
Wie bei jedem anderen Programm kann auch das Erscheinungsbild von
\fBlogin\fR
vorgespiegelt werden\&. Falls unseri\(:ose Benutzer physischen Zugriff auf den Rechner haben, kann dies von einem Angreifer verwendet werden, um das Passwort der Person zu erhalten, die sich als n\(:achste vor den Rechner setzt\&. In Linux k\(:onnen Benutzer den SAK\-Mechanismus verwenden, um einen vertrauensw\(:urdigen Pfad zu erstellen und somit diesem Angriff zu entgehen\&.
.SH "KONFIGURATION"
.PP
Die folgenden Konfigurationsvariablen in
/etc/login\&.defs
beeinflussen das Verhalten dieses Werkzeugs:
.PP
\fBCONSOLE_GROUPS\fR (Zeichenkette)
.RS 4
Liste von Gruppen, deren Mitglied der Benutzer wird, wenn der sich auf der Konsole anmeldet, die mit dem Parameter CONSOLE festgelegt wird\&. Standardm\(:a\(ssig ist die Liste leer\&.

Seien Sie vorsichtig\&. Benutzer k\(:onnen dauerhaft Zugang zu den Gruppen erlangen, auch wenn sie nicht auf der Konsole angemeldet sind\&.
.RE
.PP
\fBDEFAULT_HOME\fR (boolesch)
.RS 4
Legt fest, ob ein Login erlaubt wird, wenn mit cd nicht in das Home\-Verzeichnis gewechselt werden kann\&. Standardm\(:a\(ssig wird dies nicht zugelassen\&.
.sp
Falls auf
\fIyes\fR
gesetzt, wird der Benutzer mit dem Wurzelverzeichnis (/) angemeldet, wenn mit cd nicht in sein Home\-Verzeichnis gewechselt werden kann\&.
.RE
.PP
\fBENV_PATH\fR (Zeichenkette)
.RS 4
Wenn gesetzt, wird damit die Umgebungsvariable PATH definiert, wenn sich ein normaler Benutzer anmeldet\&. Der Wert ist eine Liste, deren Eintr\(:age durch Doppelpunkte getrennt sind (zum Beispiel
\fI/bin:/usr/bin\fR)\&. Ihr kann ein
\fIPATH=\fR
vorangestellt werden\&. Der Standardwert ist
\fIPATH=/bin:/usr/bin\fR\&.
.RE
.PP
\fBENV_SUPATH\fR (Zeichenkette)
.RS 4
Wenn gesetzt, wird damit die Umgebungsvariable PATH definiert, wenn sich der Superuser anmeldet\&. Der Wert ist eine Liste, deren Eintr\(:age durch Doppelpunkte getrennt sind (zum Beispiel
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR)\&. Ihr kann ein
\fIPATH=\fR
vorangestellt werden\&. Der Standardwert ist
\fIPATH=/sbin:/bin:/usr/sbin:/usr/bin\fR\&.
.RE
.PP
\fBERASECHAR\fR (Zahl)
.RS 4
Das L\(:oschzeichen des Terminals (\fI010\fR
= R\(:ucktaste,
\fI0177\fR
= Entf)\&.
.sp
Wenn der Wert mit \(Fc0\(Fo beginnt, wird er als Oktalzahl gewertet, wenn er mit \(Fc0x\(Fo beginnt, als Hexadezimalzahl\&.
.RE
.PP
\fBFAIL_DELAY\fR (Zahl)
.RS 4
Wartezeit in Sekunden, ehe nach einem fehlgeschlagenen Anmeldeversuch ein neuer unternommen werden kann
.RE
.PP
\fBFAKE_SHELL\fR (Zeichenkette)
.RS 4
Falls angegeben, f\(:uhrt
\fBlogin\fR
diese Shell anstelle der in
/etc/passwd
angegebenen Shell des Benutzers aus\&.
.RE
.PP
\fBHUSHLOGIN_FILE\fR (Zeichenkette)
.RS 4
Falls angegeben, kann diese Datei die \(:ubliche Informationsanzeige w\(:ahrend des Anmeldevorgangs unterbinden\&. Wenn ein vollst\(:andiger Pfad angegeben wird, wird der Modus ohne Anmeldeinformationen verwendet, wenn der Name oder die Shell des Benutzers in der Datei enthalten sind\&. Wenn kein vollst\(:andiger Pfad angegeben wird, wird der Modus ohne Anmeldeinformationen aktiviert, wenn die Datei im Home\-Verzeichnis des Benutzers existiert\&.
.RE
.PP
\fBKILLCHAR\fR (Zahl)
.RS 4
Das KILL\-Zeichen des Terminals (\fI025\fR
= CTRL/U)\&.
.sp
Wenn der Wert mit \(Fc0\(Fo beginnt, wird er als Oktalzahl gewertet, wenn er mit \(Fc0x\(Fo beginnt, als Hexadezimalzahl\&.
.RE
.PP
\fBLOGIN_RETRIES\fR (Zahl)
.RS 4
maximale Anzahl von Anmeldeversuchen, wenn ein falsches Passwort eingegeben wird
.sp
Dies wird h\(:ochstwahrscheinlich von PAM \(:uberschrieben, da standardm\(:a\(ssig das Modul pam_unix drei Versuche enth\(:alt\&. Dennoch stellt dies ein zus\(:atzliches Sicherungssystem dar, falls Sie eine Anmeldem\(:oglichkeit einsetzen, die nicht PAM_MAXTRIES beachtet\&.
.RE
.PP
\fBLOGIN_TIMEOUT\fR (Zahl)
.RS 4
H\(:ochstdauer f\(:ur einen Anmeldeversuch
.RE
.PP
\fBLOG_OK_LOGINS\fR (boolesch)
.RS 4
aktiviert die Protokollierung erfolgreicher Anmeldungen
.RE
.PP
\fBLOG_UNKFAIL_ENAB\fR (boolesch)
.RS 4
aktiviert die Anzeige unbekannter Benutzernamen, wenn fehlgeschlagene Anmeldeversuche aufgezeichnet werden
.sp
Hinweis: Das Protokollieren unbekannter Benutzernamen kann ein Sicherheitsproblem darstellen, wenn ein Benutzer sein Passwort anstelle seines Anmeldenamens eingibt\&.
.RE
.PP
\fBTTYGROUP\fR (Zeichenkette), \fBTTYPERM\fR (Zeichenkette)
.RS 4
Die Rechte des Terminals: Das Anmelde\-tty geh\(:ort der Gruppe
\fBTTYGROUP\fR
an, die Rechte werden auf
\fBTTYPERM\fR
gesetzt\&.
.sp
Standardm\(:a\(ssig ist der Eigent\(:umer des Terminals die Hauptgruppe des Benutzers, die Rechte werden auf
\fI0600\fR
gesetzt\&.
.sp
\fBTTYGROUP\fR
kann der Gruppenname oder die als Zahl ausgedr\(:uckte Gruppen\-ID sein\&.
.sp
Wenn Sie ein
\fBwrite\fR\-Programm haben, das \(Fcsetgid\(Fo f\(:ur eine Gruppe besitzt, der das Terminal geh\(:ort, sollten Sie TTYGROUP die Gruppennummer und TTYPERM den Wert 0620 zuweisen\&. Oder Sie sollten TTYGROUP als Kommentar belassen und TTYPERM den Wert 622 oder 600 zuweisen\&.
.RE
.PP
\fBTTYTYPE_FILE\fR (Zeichenkette)
.RS 4
Falls angegeben, eine Datei, welche einer tty\-Zeile den Umgebungsparameter TERM zuweist\&. Jede Zeile hat das Format wie etwa \(Fcvt100 tty01\(Fo\&.
.RE
.PP
\fBUSERGROUPS_ENAB\fR (boolesch)
.RS 4
Wenn der Wert
\fIyes\fR
ist, wird
\fBuserdel\fR
die Gruppe des Benutzers entfernen, falls sie keine Mitglieder mehr hat, und
\fBuseradd\fR
wird standardm\(:a\(ssig eine Gruppe mit dem Namen des Benutzers erstellen\&.
.RE
.SH "DATEIEN"
.PP
/var/run/utmp
.RS 4
Liste der aktuellen angemeldeten Sitzungen
.RE
.PP
/var/log/wtmp
.RS 4
Liste der vorangegangenen angemeldeten Sitzungen
.RE
.PP
/etc/passwd
.RS 4
Informationen zu den Benutzerkonten
.RE
.PP
/etc/shadow
.RS 4
verschl\(:usselte Informationen zu den Benutzerkonten
.RE
.PP
/etc/motd
.RS 4
Datei mit der Systemmeldung des Tages
.RE
.PP
/etc/nologin
.RS 4
verhindert, dass sich Benutzer au\(sser Root anmelden
.RE
.PP
/etc/ttytype
.RS 4
Liste der Terminaltypen
.RE
.PP
$HOME/\&.hushlogin
.RS 4
unterdr\(:uckt die Ausgabe von Systemnachrichten
.RE
.PP
/etc/login\&.defs
.RS 4
Konfiguration der Shadow\-Passwort\-Werkzeugsammlung
.RE
.SH "SIEHE AUCH"
.PP
\fBmail\fR(1),
\fBpasswd\fR(1),
\fBsh\fR(1),
\fBsu\fR(1),
\fBlogin.defs\fR(5),
\fBnologin\fR(5),
\fBpasswd\fR(5),
\fBsecuretty\fR(5),
\fBgetty\fR(8)\&.
