.TH QUOTAGRPADMINS 5
.SH NAME
quotagrpadmins \- users responsible for group disk usage
.SH SYNOPSIS
.B /etc/quotagrpadmins
.SH DESCRIPTION
The
.B quotagrpadmins
file lists administrators of user groups who will receive a warning if
.B warnquota --group
command finds a group exceeding its disk usage limits.
.P
Each line consists of a group name followed by a colon and a user name. White
space characters surrounding the names are allowed. Empty lines or lines
starting with a hash sign or a semicolon are ignored.
.SH EXAMPLE
.PP
# comment
.RS 0
users: root
.SH FILES
.PD 0
.TP 20
.B /etc/quotagrpadmins
list of group administrators
.PD
.SH SEE ALSO
.BR warnquota (8).
