.TH QUOTATAB 5
.SH NAME
quotatab \- Descriptions of devices with disk quotas
.SH SYNOPSIS
.B /etc/quotatab
.SH DESCRIPTION
The
.B quotatab
file lists human descriptions of devices for the purpose of
.BR warnquota (8)
notifications.
.P
Each line consists of a device path name followed by a colon and
a description. White space, apostrophe, and double quote characters
surrounding the names and descriptions will be stripped. The description field
can encode a new-line as a pipe character.
.P
Empty lines or lines starting with a hash sign or a semicolon are ignored.
.SH EXAMPLE
.PP
# comment
.RS 0
/dev/sda2: Home directories.|This becomes the second line.
.SH FILES
.PD 0
.TP 20
.B /etc/quotatab
list of device descriptions
.PD
.SH SEE ALSO
.BR warnquota (8).
