.TH ACCTON 8 "2008 November 24"
.SH NAME
accton \-  turns process accounting on or off
.SH SYNOPSIS
.hy 0
.na
.TP
.B accton
.RI [\| OPTION \|]
.RB on \||\| off \||\| filename
.TP
.B accton
[
.B \-V
|
.B \-\-version 
]
[
.B \-h
|
.B \-\-help
]
.SH DESCRIPTION
.LP
.B accton
.I filename
turns on process accounting.
.SH OPTIONS
.PD 0
.TP
.TP
.B \-V, \-\-version
Print the version number of 
.B ac
to standard output and quit.
.TP
.B \-h, \-\-help
Prints the usage string and default locations of system files to
standard output and exits.
.TP
.B on
Turns on process accounting using the default accounting file name.
.TP
.B off
Turns off process accounting.
.SH FILES
.TP
.I acct
The system wide process accounting file. See
.BR acct (5)
(or
.BR pacct (5))
for further details.
.LP
.SH AUTHOR
The GNU accounting utilities were written by Noel Cragg
<noel@gnu.ai.mit.edu>. The man page was adapted from the accounting
texinfo page by Susan Kleinmann <sgk@sgk.tiac.net>.
.SH "SEE ALSO"
.BR acct (5),
.BR ac (1)
